[versions]
kotlin = "2.4.20"
telegrambots = "10.3.0"
kotlinxSerialization = "1.11.0"

[libraries]
org-telegram-telegrambots-longpolling = { module = "org.telegram:telegrambots-longpolling", version.ref = "telegrambots" }
org-telegram-telegrambots-client = { module = "org.telegram:telegrambots-client", version.ref = "telegrambots" }
io-github-oshai-kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version = "8.0.4" }
org-apache-logging-log4j-log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version = "2.26.1" }
org-slf4j-slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.18" }
com-squareup-okhttp3-okhttp3-coroutines = { module = "com.squareup.okhttp3:okhttp-coroutines", version = "5.5.0" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.11.0" }
org-jetbrains-kotlinx-kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.8.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
